#health
- name: Check UserAPI health
  uri:
    url: http://127.0.0.1:3000/-/health
    return_content: yes
  # Register the output of the module in a variable
  register: userapi_health

- name: Print UserAPI health
  debug:
    msg: "{{ userapi_health.content }}"
