apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/CBS Computer/Downloads/ece-devops-projet-main (1)/ece-devops-projet-main"
